apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: voting-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: <YOUR_DOCKERHUB_USERNAME>/voting-backend:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-config
        volumeMounts:
        - name: rsa-keys
          mountPath: /run/secrets
          readOnly: true
      volumes:
      - name: rsa-keys
        secret:
          secretName: rsa-keys
