version: '3'

services:
  # Redis for distributed data storage and communication
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - voting-network

  # Node 1 (Leader by default)
  node1:
    build:
      context: ./node
      dockerfile: Dockerfile
    environment:
      - NODE_ID=node1
      - NODE_ROLE=leader
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_COUNT=3
    volumes:
      - ./logs/node1:/app/logs
    ports:
      - "5001:5000"
    depends_on:
      - redis
    networks:
      - voting-network

  # Node 2 (Follower)
  node2:
    build:
      context: ./node
      dockerfile: Dockerfile
    environment:
      - NODE_ID=node2
      - NODE_ROLE=follower
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_COUNT=3
    volumes:
      - ./logs/node2:/app/logs
    ports:
      - "5002:5000"
    depends_on:
      - redis
    networks:
      - voting-network

  # Node 3 (Follower)
  node3:
    build:
      context: ./node
      dockerfile: Dockerfile
    environment:
      - NODE_ID=node3
      - NODE_ROLE=follower
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_COUNT=3
    volumes:
      - ./logs/node3:/app/logs
    ports:
      - "5003:5000"
    depends_on:
      - redis
    networks:
      - voting-network

networks:
  voting-network:
    driver: bridge

volumes:
  redis-data: