FROM python:3.12-slim

WORKDIR /app

COPY node/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .
COPY auth/ ./auth/
COPY node/ ./node/

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]