version: "3.8"
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: voting
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
