version: "3.8"

secrets:
  rsa_private:
    file: ./secrets/private.pem
  rsa_public:
    file: ./secrets/public.pem

services:
  backend1:
    image: zik44/voting-backend:latest
    environment:
      - NODE_ID=node1
      - PORT=5001
    ports:
      - "5001:5001"
    env_file: .env
    secrets:
      - source: rsa_private
        target: /secrets/private.pem
      - source: rsa_public
        target: /secrets/public.pem
    depends_on:
      - redis
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  backend2:
    image: zik44/voting-backend:latest
    environment:
      - NODE_ID=node2
      - PORT=5002
    ports:
      - "5002:5002"
    env_file: .env
    secrets:
      - source: rsa_private
        target: /secrets/private.pem
      - source: rsa_public
        target: /secrets/public.pem
    depends_on:
      - redis
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: voting_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
